# Generated by Django 5.1.3 on 2024-12-18 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('en_maintenance', 'En maintenance')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('capacite', models.PositiveIntegerField()),
                ('localisation', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salles/')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.directionmodels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
