# Generated by Django 5.1.3 on 2024-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomsmodels_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsmodels',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='rooms.equipementmodels'),
        ),
    ]
