# Generated by Django 5.1.3 on 2025-01-12 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_directionmodels_options'),
        ('rooms', '0003_roomsmodels_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsmodels',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accounts.directionmodels'),
        ),
        migrations.AlterField(
            model_name='roomsmodels',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.equipementmodels'),
        ),
    ]
