# Generated by Django 5.1.3 on 2025-01-12 19:49

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomsmodels_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureRoomModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('description', models.TextField(blank=True, null=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='rooms.roomsmodels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
