# Generated by Django 5.1.3 on 2025-01-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_pictureroommodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsmodels',
            name='image',
        ),
    ]
