# Generated by Django 5.1.3 on 2025-01-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_roomsmodels_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEquipmentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipments', to='rooms.equipementmodels')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipments', to='rooms.roomsmodels')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
