# Generated by Django 5.1.3 on 2024-12-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersmodels_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionmodels',
            options={'verbose_name_plural': 'Directions'},
        ),
    ]
