# Generated by Django 5.1.3 on 2025-01-12 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_directionmodels_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionmodels',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
