# Generated by Django 5.1.3 on 2025-01-12 18:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_directionmodels_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionmodels',
            name='avatar',
        ),
        migrations.AddField(
            model_name='directionmodels',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
