# Generated by Django 5.1.3 on 2025-01-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0003_roomsmodels_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlageHoraireModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomsmodels')),
            ],
        ),
    ]
