# Generated by Django 5.1.3 on 2025-01-10 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_plagehorairemodels'),
        ('rooms', '0003_roomsmodels_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingroomsmodels',
            options={'ordering': ['date', 'heure_debut']},
        ),
        migrations.RenameField(
            model_name='bookingroomsmodels',
            old_name='statut',
            new_name='etat',
        ),
        migrations.AddConstraint(
            model_name='bookingroomsmodels',
            constraint=models.UniqueConstraint(fields=('salle', 'date', 'heure_debut', 'heure_fin'), name='unique_booking_constraint'),
        ),
    ]
