# Generated by Django 5.1.3 on 2025-01-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingroomsmodels_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagehorairemodels',
            name='heure_debut',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='plagehorairemodels',
            name='heure_fin',
            field=models.CharField(max_length=5),
        ),
    ]
