# Generated by Django 5.1.3 on 2025-01-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_directionmodels_options'),
        ('bookings', '0004_alter_plagehorairemodels_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroomsmodels',
            name='direction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.directionmodels'),
            preserve_default=False,
        ),
    ]
