# Generated by Django 5.1.3 on 2025-01-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingroomsmodels_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroomsmodels',
            name='direction',
        ),
    ]
