# Generated by Django 5.1.3 on 2025-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_bookingroomsmodels_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroomsmodels',
            name='etat',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('rejete', 'Rejetee'), ('annulee', 'Annulee'), ('libere', 'Libere')], default='en_attente', max_length=20),
        ),
    ]
